server: 
  extraArgs:
    web.enable-remote-write-receiver: ""

serverFiles:
  prometheus.yml:
    scrape_configs: [] # consider removing this to use prometheus k8s scraping, or leaving this to use otelco k8s scraping

kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false