apiVersion: apps/v1
kind: Deployment
metadata:
    name: dolphin-deployment
    labels:
        app: dolphin-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dolphin-deployment
    template:
        metadata:
            labels:
                app: dolphin-deployment
        spec:
            containers:
                - name: deployment
                  image: "supahakka/deployment:v3"
                  imagePullPolicy: {{ .Values.imagePullPolicy }}
                  # imagePullPolicy: Always
                  env:
                    - name: OTEL_PYTHON_LOG_LEVEL
                      value: "debug"
                    - name: OTEL_EXPORTER_OTLP_ENDPOINT
                      value: "otelcol-deploymentset-hehe-opentelemetry-collector:4317"
                    - name: OTEL_EXPORTER_OTLP_INSECURE
                      value: "true"
                    - name: OTEL_SERVICE_NAME
                      value: "dolphin-deployment-service"
                    - name: OTEL_METRICS_EXPORTER
                      value: "otlp"
                    - name: OTEL_TRACES_EXPORTER
                      value: "otlp"
                    - name: OTEL_LOGS_EXPORTER
                      value: "otlp"
                    - name: OTEL_PYTHON_LOG_CORRELATION
                      value: "true"
                    - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
                      value: "true"
                  ports:
                      - containerPort: 15004
                  livenessProbe:
                    httpGet:
                      scheme: HTTPS
                      path: /liveness
                      port: 15004
                    initialDelaySeconds: 30
                    periodSeconds: 10
                  readinessProbe:
                    httpGet:
                      scheme: HTTPS
                      path: /readiness
                      port: 15004
                    initialDelaySeconds: 30
                    periodSeconds: 10
                  startupProbe:
                    httpGet:
                      scheme: HTTPS
                      path: /health
                      port: 15004
                    initialDelaySeconds: 30
                    periodSeconds: 10
                    failureThreshold: 10
                  volumeMounts:
                      - name: config-volume
                        mountPath: /app/env/
                      - name: tls-secret
                        mountPath: /app/certs/
                      #   subPath: tls.crt
                      # - name: tls-secret
                      #   mountPath: /app/
                      #   subPath: tls.key
                      # - name: tls-secret
                      #   mountPath: /app/
                      #   subPath: ca.crt
                      - name: seldon-controlplane-client-tls-secret
                        mountPath: /app/seldon/
            volumes:
              - name: config-volume
                configMap:
                    name: dolphin-microservices-config
                    # items:
                    #   - key: .env
                    #     path: .env
              - name: tls-secret
                secret:
                    secretName: dolphin-deployment-tls-secret
              - name: seldon-controlplane-client-tls-secret
                secret:
                    secretName: seldon-controlplane-client-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dolphin-deployment-service
  labels:
    app: dolphin-deployment
spec:
  selector:
    app: dolphin-deployment
  ports:
    - protocol: TCP
      port: 15004
      targetPort: 15004