apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: dolphin-ns
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "microservices-hehe"
    meta.helm.sh/release-namespace: "dolphin-ns"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dolphin-gateway
    http:
      paths:
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: keycloak-dolphin-service
      #       port:
      #         number: 443
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: keycloak-dolphin-service
      #       port:
      #         number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dolphin-web-service
            port:
              number: 14999