apiVersion: apps/v1
kind: Deployment
metadata:
    name: dolphin-jobs-monitor
    labels:
        app: dolphin-jobs-monitor
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dolphin-jobs-monitor
    template:
        metadata:
            labels:
                app: dolphin-jobs-monitor
        spec:
            containers:
                - name: jobs-monitor
                  image: "supahakka/jobs-monitor:v2"
                  env:
                    - name: OTEL_PYTHON_LOG_LEVEL
                      value: "debug"
                    - name: OTEL_EXPORTER_OTLP_ENDPOINT
                      value: "otel-collector:4317"
                    - name: OTEL_EXPORTER_OTLP_INSECURE
                      value: "true"
                    - name: OTEL_SERVICE_NAME
                      value: "app-model-management"
                    - name: OTEL_METRICS_EXPORTER
                      value: "otlp,console"
                    - name: OTEL_TRACES_EXPORTER
                      value: "otlp,console"
                    - name: OTEL_LOGS_EXPORTER
                      value: "console,otlp"
                    - name: OTEL_PYTHON_LOG_CORRELATION
                      value: "true"
                    - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
                      value: "true"
                  ports:
                      - containerPort: 15002
                  volumeMounts:
                      - name: config-volume
                        mountPath: /app/env/
                        subpath: .env
                      - name: tls-secret
                        mountPath: /app/certs/
                      #   subPath: tls.crt
                      # - name: tls-secret
                      #   mountPath: /app/
                      #   subPath: tls.key
                      # - name: tls-secret
                      #   mountPath: /app/
                      #   subPath: ca.crt
            volumes:
              - name: config-volume
                configMap:
                    name: dolphin-microservices-config
                    # items:
                    #   - key: .env
                    #     path: .env
              - name: tls-secret
                secret:
                    secretName: dolphin-jobs-monitor-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dolphin-jobs-monitor-service
  labels:
    app: dolphin-jobs-monitor
spec:
  selector:
    app: dolphin-jobs-monitor
  ports:
    - protocol: TCP
      port: 15002
      targetPort: 15002