apiVersion: apps/v1
kind: Deployment
metadata:
    name: dolphin-orchestration
    labels:
        app: dolphin-orchestration
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dolphin-orchestration
    template:
        metadata:
            labels:
                app: dolphin-orchestration
        spec:
            containers:
                - name: orchestration
                  image: "supahakka/orchestration:v3"
                  imagePullPolicy: Always
                  env:
                    - name: OTEL_PYTHON_LOG_LEVEL
                      value: "debug"
                    - name: OTEL_EXPORTER_OTLP_ENDPOINT
                      value: "otelcol-deploymentset-hehe-opentelemetry-collector:4317"
                    - name: OTEL_EXPORTER_OTLP_INSECURE
                      value: "true"
                    - name: OTEL_SERVICE_NAME
                      value: "app-model-management"
                    - name: OTEL_METRICS_EXPORTER
                      value: "otlp"
                    - name: OTEL_TRACES_EXPORTER
                      value: "otlp"
                    - name: OTEL_LOGS_EXPORTER
                      value: "otlp"
                    - name: OTEL_PYTHON_LOG_CORRELATION
                      value: "true"
                    - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
                      value: "true"
                  ports:
                      - containerPort: 15001
                  volumeMounts:
                      - name: config-volume
                        mountPath: /app/env/
                      - name: tls-secret
                        mountPath: /app/certs/
                      #   subPath: tls.crt
                      # - name: tls-secret
                      #   mountPath: /app/
                      #   subPath: tls.key
                      # - name: tls-secret
                      #   mountPath: /app/
                      #   subPath: ca.crt
            volumes:
              - name: config-volume
                configMap:
                    name: dolphin-microservices-config
                    # items:
                    #   - key: .env
                    #     path: .env
              - name: tls-secret
                secret:
                    secretName: dolphin-orchestration-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dolphin-orchestration-service
  labels:
    app: dolphin-orchestration
spec:
  selector:
    app: dolphin-orchestration
  ports:
    - protocol: TCP
      port: 15001
      targetPort: 15001