apiVersion: v1
kind: Secret
metadata:
  name: minio-seldon-secret
type: Opaque
stringData:
  s3: |
    type: s3
    name: s3
    parameters:
      provider: minio
      env_auth: false
      access_key_id: admin_minio
      secret_access_key: admin_minio
      endpoint: http://minio-dolphin:9000