---
- name: Deploy Helm Charts on Kubernetes
  hosts: localhost
  # vars:
  vars_files:
    - vars.ansible.yaml
  tasks:
    - name: Ensure Helm is installed
      ansible.builtin.command: helm version
      register: helm_version
      failed_when: helm_version.rc != 0
      changed_when: false

    - name: Deploy seldon-core-v2-setup Helm chart
      ansible.builtin.command: >
        helm install seldon-core-v2-setup-hehe . -f 2_setup_values.yaml
      args:
        chdir: "helm/seldon-core-v2-setup"
      register: seldon_core_v2_setup_install
      changed_when: "'STATUS: deployed' in seldon_core_v2_setup_install.stdout"

    - name: Deploy Helm chart
      ansible.builtin.command: >
        helm install {{ item.release }} . -f {{ item.values_file }}
      args:
        chdir: "{{ item.chart_path }}"
      register: helm_install
      changed_when: "'STATUS: deployed' in helm_install.stdout"
      loop: "{{ charts }}"
      loop_control:
        loop_var: item

    - name: Verify Helm release
      ansible.builtin.command: helm status {{ item.release }}
      register: helm_status
      changed_when: false
      failed_when: helm_status.rc != 0
      loop: "{{ charts }}"
      loop_control:
        loop_var: item

    - name: Get ClusterIP of keycloak-dolphin-service
      ansible.builtin.command: kubectl get svc keycloak-dolphin-service -o jsonpath='{.spec.clusterIP}'
      register: keycloak_cluster_ip
      changed_when: false

    - name: Get ClusterIP of grafana-dolphin-service
      ansible.builtin.command: kubectl get svc grafana-dolphin-service -o jsonpath='{.spec.clusterIP}'
      register: grafana_cluster_ip
      changed_when: false

    - name: Update KEYCLOAK_SERVER_URL in .env file
      ansible.builtin.replace:
        path: helm/microservices/files/.env
        regexp: 'KEYCLOAK_SERVER_URL="https://[^:]+'
        replace: 'KEYCLOAK_SERVER_URL="https://{{ keycloak_cluster_ip.stdout }}'

    - name: Update GRAFANA_UI_URL in .env file
      ansible.builtin.replace:
        path: helm/microservices/files/.env
        regexp: 'GRAFANA_UI_URL="http://[^:]+'
        replace: 'GRAFANA_UI_URL="http://{{ grafana_cluster_ip.stdout }}'

    - name: Deploy microservices
      ansible.builtin.command: >
        helm install microservices-hehe . -f values.yaml
      args:
        chdir: "helm/microservices"
      register: microservices_deploy
      changed_when: "'STATUS: deployed' in microservices_deploy.stdout"
