---
- name: Deploy Helm Charts on Kubernetes
  hosts: localhost
  # vars:
  vars_files:
    - vars.ansible.yaml
  tasks:
    - name: Ensure Helm is installed
      ansible.builtin.command: helm version
      register: helm_version
      failed_when: helm_version.rc != 0
      changed_when: false

    # - name: Deploy seldon-core-v2-setup Helm chart
    #   ansible.builtin.command: >
    #     helm install seldon-core-v2-setup-hehe . -f 2_setup_values.yaml --wait
    #   args:
    #     chdir: "helm/seldon-core-v2-setup"
    #   register: seldon_core_v2_setup_install
    #   changed_when: "'STATUS: deployed' in seldon_core_v2_setup_install.stdout"

    - name: Deploy Helm chart
      ansible.builtin.command: >
        helm install {{ item.release }} . -f {{ item.values_file }}
        {% if 'airflow' not in item.chart_path %} --wait {% endif %}
      args:
        chdir: "{{ item.chart_path }}"
      register: helm_install
      changed_when: "'STATUS: deployed' in helm_install.stdout"
      loop: "{{ charts }}"
      loop_control:
        loop_var: item

    - name: Verify Helm release
      ansible.builtin.command: helm status {{ item.release }}
      register: helm_status
      changed_when: false
      failed_when: helm_status.rc != 0
      loop: "{{ charts }}"
      loop_control:
        loop_var: item
