
minio: 
  auth: 
    rootUser: admin
    rootPassword: admin123

tracking: 
  auth: 
    enabled: false
  service: 
    type: ClusterIP

postgresql:
  auth: 
    username: bn_mlflow
    password: bn_mlflow
