mode: deployment

fullnameOverride: otelcol-deploymentset-hehe-opentelemetry-collector

image:
  repository: otel/opentelemetry-collector-contrib

# We only want one of these collectors - any more and we'd produce duplicate data
replicaCount: 1

presets:
  # enables the k8sclusterreceiver and adds it to the metrics pipelines
  clusterMetrics:
    enabled: true
  # enables the k8sobjectsreceiver to collect events only and adds it to the logs pipelines
  kubernetesEvents:
    enabled: true

config:
  exporters:
    debug: {}

    otlp/jaeger-grpc:
      endpoint: http://jaeger-dolphin-service-collector:4317
      tls: 
        insecure: true

    otlphttp: # this must be correct and not arbitrary. the name after the / can be though.
      endpoint: http://loki-dolphin-service-distributor:3100/otlp
      tls: 
        insecure: true

    prometheusremotewrite:
      endpoint: "http://prometheus-dolphin-service:9090/api/v1/write"
      tls: 
        insecure: true
      # wal: # Enabling the Write-Ahead-Log for the exporter.
      #   directory: ./prom_rw # The directory to store the WAL in
      #   buffer_size: 100 # Optional count of elements to be read from the WAL before truncating; default of 300
      #   truncate_frequency: 45s # Optional frequency for how often the WAL should be truncated. It is a time.ParseDuration; default of 1m
      # resource_to_telemetry_conversion:
      #   enabled: true # Convert resource attributes to metric labels



  service: 
    pipelines:
      logs:
        exporters:
          - debug
          - otlphttp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - debug
          - prometheusremotewrite
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - debug
          - otlp/jaeger-grpc
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - jaeger
          - zipkin