fullnameOverride: keycloak-dolphin-service


image: 
  tag: 26.0.5-debian-12-r0 # MUST BE THIS TAG or later OTHERWISE REALM IMPORT WILL GET FUCKED!!!!


service: 
  type: LoadBalancer
  # loadBalancerIP: "10.108.237.147"
  # clusterIP: "10.96.12.153"
  
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    # value: --import-realm
    value: "--import-realm"
  # - name: KEYCLOAK_LOG_LEVEL
  #   value: DEBUG

extraVolumes:
  - name: realm-config
    configMap:
      name: dolphin-realm-configmap 
  - name: bundle-inject
    configMap:
      name: dolphin-trusted-ca-bundle
      items:
        - key: root-certs.pem
          path: ca-certificates.crt # must overwrite "/etc/ssl/certs/ca-certificates.crt" on debian

extraVolumeMounts:
  - name: realm-config
    mountPath: /opt/bitnami/keycloak/data/import
    readOnly: true
  - name: bundle-inject
    mountPath: /etc/ssl/certs/
    readOnly: true

auth:
  adminUser: admin
  adminPassword: admin


postgresql:
  enabled: false
  
externalDatabase:
  host: postgresql-dolphin-service
  port: 5432
  user: bn_keycloak
  password: supahakka
  database: bitnami_keycloak


# BOTH TLS AND SPI TRUST STORE SETTINGS MUST BE SPECIFIED OTHERWISE YOU ARE FUCKED!
tls: 
  enabled: true
  existingSecret: keycloak-tls-secret
  keystoreFilename: keystore.jks
  truststoreFilename: truststore.jks
  keystorePassword: lmaohehe
  truststorePassword: lmaohehe
spi:
  existingSecret: keycloak-tls-secret
  truststorePassword: lmaohehe
  truststoreFilename: truststore.jks






# extraStartupArgs: >-
#   --spi-truststore-file-file=/test/tls/truststore.jks
#   --spi-truststore-file-password=lmaohehe
#   --spi-truststore-file-hostname-verification-policy=WILDCARD