apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-spark-dummy-deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-spark-dummy-deployment-test
  template:
    metadata:
      labels:
        app: mlflow-spark-dummy-deployment-test
    spec:
      containers:
      - name: mlflow-spark-dummy-deployment-test
        image: supahakka/mlflow-run:v7
        env: 
        - name: MLFLOW_TRACKING_URI
          value: https://mlflow-dolphin-service-tracking:443
          
        - name: MLFLOW_TRACKING_SERVER_CERT_PATH
          value: /etc/ssl/certs/ca-certificates.crt
        - name: MLFLOW_TRACKING_USERNAME
          value: mlflow
        - name: MLFLOW_TRACKING_PASSWORD
          value: mlflow

        # - name: MLFLOW_S3_ENDPOINT_URL
        #   value: http://mlflowtest-minio:80
        # - name: AWS_ACCESS_KEY_ID
        #   value: admin
        # - name: AWS_SECRET_ACCESS_KEY
        #   value: admin123

        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
              
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - mountPath: /mnt/host-folder
          name: host-folder
        - mountPath: /opt/bitnami/spark/tmp
          name: nfs-volume
        - mountPath: /etc/ssl/certs/
          name: dolphin-ca-bundle
          readOnly: true
      volumes:
      - name: host-folder
        hostPath:
          path: /mnt/host-folder
          type: Directory
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: dolphin-ca-bundle
        configMap:
          name: dolphin-trusted-ca-bundle
          items:
          - key: root-certs.pem
            path: ca-certificates.crt