fullnameOverride: kafka-dolphin-service

controller: 
  replicaCount: 2
  persistence:
    enabled: false

extraVolumes:
  - name: bundle-inject
    configMap:
      name: dolphin-trusted-ca-bundle
      items:
        - key: root-certs.pem
          path: ca-certificates.crt # must overwrite "/etc/ssl/certs/ca-certificates.crt" on debian

extraVolumeMounts:
  - name: bundle-inject
    mountPath: /etc/ssl/certs/
    readOnly: true

tls: 
  type: JKS
  existingSecret: kafka-tls-secret
  jksKeystoreKey: keystore.jks
  keystorePassword: lmaohehe
  jksTruststoreKey: truststore.jks
  truststorePassword: lmaohehe
  sslClientAuth: none

listeners: 
  client: 
    name: CLIENT_DOLPHIN
    protocol: SASL_SSL
  
  controller: 
    name: CONTROLLER_DOLPHIN
    protocol: SASL_SSL # SASL_SSL, SASL_PLAINTEXT, SSL, PLAINTEXT

  interbroker:
    name: INTERBROKER_DOLPHIN
    protocol: SASL_SSL

sasl: 
  enabledMechanisms: "PLAIN,SCRAM-SHA-256,SCRAM-SHA-512"
  interbroker: 
    user: kafka-interbroker-user
    password: kafka-interbroker-password
  controller: 
    user: kafka-controller-user
    password: kafka-controller-password
  client:
    users:
      - seldon 
      # - user2
      # - user3
    passwords: 
      - seldonPassword
      # - password2
      # - password3

