apiVersion: v1
kind: Service
metadata:
  name: bridge-to-k8s-dummy-service
  namespace: dolphin-ns
spec:
  selector:
    app: bridge-to-k8s-dummy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-to-k8s-dummy-deployment
  namespace: dolphin-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-to-k8s-dummy
  template:
    metadata:
      labels:
        app: bridge-to-k8s-dummy
    spec:
      containers:
        - name: bridge-to-k8s-dummy-container
          image: nginx
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      #     volumeMounts:
      #       - mountPath: /etc/ssl/certs/
      #         name: ca-roor-certs-bundle
      #         readOnly: true
      # volumes:
      #   - name: ca-roor-certs-bundle
      #     configMap:
      #       name: dolphin-trusted-ca-bundle 
      #       items:
      #       - key: root-certs.pem
      #         path: ca-certificates.crt # must overwrite "/etc/ssl/certs/ca-certificates.crt" on debian