apiVersion: v1
kind: ConfigMap
metadata:
    name: {{include "openldap.configmap-init-files" .}}
data:
    init.ldif: |
        {{ .Files.Get "files/init.ldif" | nindent 8 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{include "openldap.configmap-env" .}}
data:
    LDAP_PORT_NUMBER: {{ .Values.LDAP_PORT_NUMBER | quote}}
    LDAP_ENABLE_TLS: "yes"
    LDAP_TLS_CERT_FILE: /etc/ldap/ssl/tls.crt
    LDAP_TLS_KEY_FILE: /etc/ldap/ssl/tls.key
    LDAP_TLS_CA_FILE: /etc/ldap/ssl/ca.crt
