apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    {{include "openldap.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- include "openldap.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openldap.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "bitnami/openldap:latest"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{include "openldap.configmap-env" .}}
            - secretRef:
                name: {{include "openldap.secrets" .}}
        
          # env:
          #   - name: LDAP_TLS_CERT_FILE
          #     value: /etc/ldap/ssl/my-org-new.crt
          #   - name: LDAP_TLS_KEY_FILE
          #     value: /etc/ldap/ssl/my-org-new.key
          #   - name: LDAP_TLS_CA_FILE
          #     value: /etc/ldap/ssl/my-org.com.crt
          ports:
            - name: ldap
              containerPort: {{ .Values.LDAP_PORT_NUMBER }}
              protocol: TCP
          volumeMounts:
            - name: openldap-data
              mountPath: /bitnami/openldap
            - name: openldap-config
              mountPath: /ldifs
            - name: openldap-tls
              mountPath: "/etc/ldap/ssl"
              readOnly: true
            - mountPath: /etc/ssl/certs/
              name: ca-roor-certs-bundle
              readOnly: true
      volumes:
        - name: openldap-tls
          secret:
            secretName: openldap-tls-secret
        - name: openldap-data
          emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: openldap-data
        - name: openldap-config
          configMap:
            name: {{include "openldap.configmap-init-files" .}}
            # items: # not specifying items will mount all keys in the configmap into files in a directory
            #   - key: init.ldif
        - name: ca-roor-certs-bundle
          configMap:
            name: dolphin-bundle
            # defaultMode: 0644
            # optional: false
            items:
            - key: root-certs.pem
              path: ca-certificates.crt # must overwrite "/etc/ssl/certs/ca-certificates.crt" on debian
