apiVersion: v1
kind: Secret
metadata:
  name: {{include "openldap.secrets" .}}
type: Opaque
data:
  LDAP_ADMIN_USERNAME: {{ .Values.secrets.LDAP_ADMIN_USERNAME | b64enc }}
  LDAP_ADMIN_PASSWORD: {{ .Values.secrets.LDAP_ADMIN_PASSWORD | b64enc }}
  LDAP_ROOT: {{ .Values.secrets.LDAP_ROOT | b64enc }} 

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: openldap-tls
# type: Opaque
# data:
#   openldap.key: |-
#     {{ .Files.Get "certs/my-org-new.key" | b64enc }}
#   openldap.crt: |-
#     {{ .Files.Get "certs/my-org-new.crt" | b64enc }}
#   openldapCA.crt: |-
#     {{ .Files.Get "certs/my-org.com.crt" | b64enc }}