apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: PC9A941E8F2E49454
          matcherRegex: trace_id
          name: Trace
          matcherType: "label"
          label: trace_id
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"