# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: kubeconfig-generator
#   namespace: dolphin-ns

# --- 

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: kubeconfig-generator-role
# rules:
# - apiGroups: [""]
#   resources: ["configmaps", "secrets"]
#   verbs: ["get", "list"]
# - apiGroups: ["batch.volcano.sh"]
#   resources: ["jobs", "jobs/status"]
#   verbs: ["create", "get", "list", "watch"]

# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: kubeconfig-generator-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: kubeconfig-generator-role
# subjects:
# - kind: ServiceAccount
#   name: kubeconfig-generator
#   namespace: dolphin-ns

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeconfig-generator-admin
  namespace: dolphin-ns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeconfig-generator-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeconfig-generator-admin
  namespace: dolphin-ns
