apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: supahakka/dolphin-spark:with-username
          ports:
            - containerPort: 8080
            - containerPort: 7077
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflowtest-tracking:80"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://mlflowtest-minio:80"
            - name: AWS_ACCESS_KEY_ID
              value: "admin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "admin123"
          volumeMounts:
            - name: nfs-volume
              mountPath: /opt/bitnami/spark/tmp
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: supahakka/dolphin-spark:with-username
          ports:
            - containerPort: 8081
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER_URL
              value: spark://spark-master-svc:7077
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflowtest-tracking:80"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://mlflowtest-minio:80"
            - name: AWS_ACCESS_KEY_ID
              value: "admin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "admin123"
          volumeMounts:
            - name: nfs-volume
              mountPath: /opt/bitnami/spark/tmp
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
spec:
  selector:
    app: spark
    role: master
  ports:
    - name: spark-master-port
      protocol: TCP
      port: 7077
      targetPort: 7077
    - name: spark-web-ui
      protocol: TCP
      port: 8080
      targetPort: 8080


