mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
# command:
#   name: "otelcol"

presets:
  # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
  kubernetesAttributes:
    enabled: true
  # enables the kubeletstatsreceiver and adds it to the metrics pipelines
  kubeletMetrics:
    enabled: true
  # Enables the filelogreceiver and adds it to the logs pipelines
  logsCollection:
    enabled: true


## The chart only includes the loggingexporter by default
## If you want to send your data somewhere you need to
## configure an exporter, such as the otlpexporter
# config:
# exporters:
#   otlp:
#     endpoint: "<SOME BACKEND>"
# service:
#   pipelines:
#     traces:
#       exporters: [ otlp ]
#     metrics:
#       exporters: [ otlp ]
#     logs:
#       exporters: [ otlp ]

service: 
  enabled: true

config:
  exporters:
    debug: {}

    otlp/jaeger-grpc:
      endpoint: http://jaegertest-collector:4317
      tls: 
        insecure: true

    otlphttp: # this must be correct and not arbitrary. the name after the / can be though.
      endpoint: http://lokitest-grafana-loki-distributor:3100/otlp
      tls: 
        insecure: true

    # prometheus:
    #   endpoint: "0.0.0.0:9999"
    #   # tls:
    #   #   ca_file: "/path/to/ca.pem"
    #   #   cert_file: "/path/to/cert.pem"
    #   #   key_file: "/path/to/key.pem"
    #   # namespace: test-space
    #   const_labels:
    #     label1: value1
    #     # "another label": spaced value
    #   send_timestamps: true
    #   metric_expiration: 180m
    #   enable_open_metrics: true
    #   add_metric_suffixes: false
    #   resource_to_telemetry_conversion:
    #     enabled: true

    prometheusremotewrite:
      endpoint: "http://promtest-prometheus-server:80/api/v1/write"
      tls: 
        insecure: true
      # wal: # Enabling the Write-Ahead-Log for the exporter.
      #   directory: ./prom_rw # The directory to store the WAL in
      #   buffer_size: 100 # Optional count of elements to be read from the WAL before truncating; default of 300
      #   truncate_frequency: 45s # Optional frequency for how often the WAL should be truncated. It is a time.ParseDuration; default of 1m
      # resource_to_telemetry_conversion:
      #   enabled: true # Convert resource attributes to metric labels

  # receivers:
  #   otlp/notls:


  service: 
    pipelines:
      logs:
        exporters:
          - debug
          - otlphttp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - debug
          - prometheusremotewrite
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - debug
          - otlp/jaeger-grpc
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - jaeger
          - zipkin