apiVersion: v1
kind: Secret
metadata:
  name: dolphin-ca-key-cert
data:
  tls.crt: {{ .Files.Get "files/rootCA/dolphin.rootCA.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/rootCA/dolphin.rootCA.key" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: dolphin-jks-keystore-password 
data:
  password: {{ .Values.jks_keystore_password | b64enc }}