
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dolphin-model-management
spec:
  secretName: dolphin-model-management-tls-secret
  duration: 9760h 
  renewBefore: 8760h
  isCA: false
  usages:
    - server auth
    - client auth
    - digital signature
  subject:
    organizations:
      - cert-manager
  commonName: dolphin-model-management-service
  dnsNames:
    - dolphin-model-management-service.dolphin-ns.svc.cluster.local
    - dolphin-model-management-service
  issuerRef:
    name: dolphin-ca-issuer
    kind: Issuer