apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-hehe 
spec:
  # Secret names are always required.
  secretName: postgresql-tls-secret

  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  # secretTemplate:
  #   annotations:
  #     app-annotation: dolphin
  #   labels:
  #     app-label: dolphin

  # privateKey:
  #   algorithm: RSA
  #   encoding: PKCS1
  #   size: 2048

  # keystores:
  #   # keystore.jks contains the private key and the certificate
  #   # truststore.jks contains the issuer certificate 
  #   jks:
  #     create: true
  #     alias: certificate # the default alias of the key in the keystore
  #     passwordSecretRef: # this must be a sreference to an existing k8s secret
  #       name: dolphin-jks-keystore-password 
  #       key: password

  duration: 9760h 
  renewBefore: 8760h # 365d

  isCA: false
  usages:
    - server auth
    - client auth
    - digital signature

  subject:
    organizations:
      - cert-manager

  # Avoid using commonName for DNS names in end-entity (leaf) certificates. Unless you have a specific
  # need for it in your environment, use dnsNames exclusively to avoid issues with commonName.
  # Usually, commonName is used to give human-readable names to CA certificates and can be avoided for
  # other certificates.
  commonName: postgresql-dolphin-service

  # The literalSubject field is exclusive with subject and commonName. It allows
  # specifying the subject directly as a string. This is useful for when the order
  # of the subject fields is important or when the subject contains special types
  # which can be specified by their OID.
  #
  # literalSubject: "O=jetstack, CN=example.com, 2.5.4.42=John, 2.5.4.4=Doe"

  # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames: # must match the fullNameOverride
    - postgresql-dolphin-service.dolphin-ns.svc.cluster.local
    - postgresql-dolphin-service
    - postgresql-dolphin-service-hl
#   uris:
#     - spiffe://cluster.local/ns/sandbox/sa/example
#   emailAddresses:
#     - john.doe@cert-manager.io
#   ipAddresses:
#     - 192.168.0.5
  # Needs cert-manager 1.14+ and "OtherNames" feature flag
#   otherNames:
#     # Should only supply oid of ut8 valued types
#     - oid: 1.3.6.1.4.1.311.20.2.3 # User Principal Name "OID"
#       utf8Value: upn@example.local

  # Issuer references are always required.
  issuerRef:
    name: dolphin-ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    # group: cert-manager.io