apiVersion: rbac.authorization.k8s.io/v1
# this is probably not needed, but it's here for reference
kind: Role
metadata:
  namespace: dolphin-ns
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "configmaps", "secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: dolphin-ns
subjects:
- kind: ServiceAccount
  name: {{ include "spark.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io