apiVersion: v1
kind: Secret
metadata:
  name: dolphin-ca-key-cert
  namespace: cert-manager # must be the same namespace as the trust-manager
data:
  tls.crt: {{ .Files.Get "files/rootCA/dolphin.rootCA.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/rootCA/dolphin.rootCA.key" | b64enc }}