# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: openldap-data
#   labels:
#         {{- include "openldap.labels" . | nindent 8 }}
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/mnt/openldap"

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: openldap-data
#   labels:
#         {{- include "openldap.labels" . | nindent 8 }}
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi