apiVersion: v1
kind: ConfigMap
metadata:
    name: {{include "openldap.configmap-init-files" .}}
data:
    init.ldif: |
        {{ .Files.Get "files/init.ldif" | nindent 8 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{include "openldap.configmap-env" .}}
data:
    LDAP_PORT_NUMBER: {{ .Values.LDAP_PORT_NUMBER | quote}}

