apiVersion: v1
kind: Secret
metadata:
  name: {{include "openldap.secrets" .}}
type: Opaque
data:
  LDAP_ADMIN_USERNAME: {{ .Values.secrets.LDAP_ADMIN_USERNAME | b64enc }}
  LDAP_ADMIN_PASSWORD: {{ .Values.secrets.LDAP_ADMIN_PASSWORD | b64enc }}
  LDAP_ROOT: {{ .Values.secrets.LDAP_ROOT | b64enc }} 