apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: dolphin-ns
spec:
  selector:
    app: dummy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
  namespace: dolphin-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy-container
          image: nginx
          ports:
            - containerPort: 8080