global:
  resolve_timeout: 5m

route:
  receiver: 'webhook'
  group_by: ['alertname', 'model']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://host.docker.internal:8000/alert'