channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.3.1
- pip:
  - mlflow==2.17.2
  - attrs==24.2.0
  - click==8.1.7
  - openai==1.54.0
  - rich==13.9.4
  - tenacity==9.0.0
  - tiktoken==0.8.0
name: mlflow-env
