services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - './create_mlflowdb.sql:/docker-entrypoint-initdb.d/create_mlflowdb.sql'

    networks:
      - shared_network
    ports:
      - "5432:5432"

  keycloak:
    image: bitnami/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_PASSWORD=admin
      
      - KEYCLOAK_SPI_TRUSTSTORE_FILE=/certs/truststore.jks
      - KEYCLOAK_SPI_TRUSTSTORE_PASSWORD=lmaohehe

      # - KEYCLOAK_ENABLE_HTTPS=true
      # - KEYCLOAK_HTTPS_USE_PEM=true  # need this shit!
      # - KEYCLOAK_HTTPS_CERTIFICATE_FILE=/certs/dolphin.rootCA.crt
      # - KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE=/certs/dolphin.rootCA.key
    ports:
      - "18080:8080"
      - "18443:8443"
    volumes:
      - ./certs:/certs
      - ./realms:/realms
      - ./kc-init.sh:/docker-entrypoint-initdb.d/kc-init.sh
    depends_on:
      - openldap
      - postgresql
    networks:
      - shared_network

  openldap:
    image: bitnami/openldap:latest
    environment:
      - LDAP_ADMIN_USERNAME=topg
      - LDAP_ADMIN_PASSWORD=supahakka
      - LDAP_PORT_NUMBER=389
      - LDAP_ROOT=dc=dolphin,dc=lmao
      # - LDAP_LOGLEVEL=-1

      - LDAP_ENABLE_TLS=yes
      - LDAP_REQUIRE_TLS=yes
      # - LDAP_LDAPS_PORT_NUMBER=1636
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt  # need to chmod and need not cert and ca be diff
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/dolphin.rootCA.crt
      - BITNAMI_DEBUG=true
      # - LDAP_TLS_VERIFY_CLIENT=never
    ports:
      # - "389:389"
      - "636:1636" # keycloak can't use starttls ports that aren't 636
    volumes:
      - ./certs:/opt/bitnami/openldap/certs
      - ./ldap-config:/ldifs
    networks:
      - shared_network

  # phpldapadmin:
  #   image: osixia/phpldapadmin:latest
  #   environment:
  #     - PHPLDAPADMIN_LDAP_HOSTS=openldap
  #     - PHPLDAPADMIN_HTTPS=false
  #   ports:
  #     - "6443:443"
  #     - "8081:80"
  #   depends_on:
  #     - openldap
  #   networks:
  #     - shared_network

  redis:
    image: bitnami/redis:latest
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=dolphin_redis_password
      - REDIS_TLS_CERT_FILE=/certs/dolphin.rootCA.crt
      - REDIS_TLS_KEY_FILE=/certs/dolphin.rootCA.key
      - REDIS_TLS_CA_FILE=/certs/dolphin.rootCA.crt
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_AUTH_CLIENTS=no
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis'
      - ./certs:/certs
    networks:
      - shared_network

volumes:
  postgresql_data:
  redis_data:

networks:
  shared_network:
    external: true