services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - './create_mlflowdb.sql:/docker-entrypoint-initdb.d/create_mlflowdb.sql'

    networks:
      - shared_network
    ports:
      - "5432:5432"

  keycloak:
    image: bitnami/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms:/realms
      - ./kc-init.sh:/docker-entrypoint-initdb.d/kc-init.sh
    depends_on:
      - openldap
      - postgresql
    networks:
      - shared_network

  openldap:
    image: bitnami/openldap:latest
    environment:
      - LDAP_ADMIN_USERNAME=topg
      - LDAP_ADMIN_PASSWORD=supahakka
      - LDAP_LDAPS_PORT_NUMBER=636
      - LDAP_PORT_NUMBER=389
      - LDAP_ROOT=dc=dolphin,dc=lmao
      - LDAP_LOGLEVEL=8
      # - LDAP_TLS_VERIFY_CLIENT=never
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap-config:/ldifs
    networks:
      - shared_network

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "6443:443"
      - "8081:80"
    depends_on:
      - openldap
    networks:
      - shared_network

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis'
    networks:
      - shared_network

volumes:
  postgresql_data:
  redis_data:

networks:
  shared_network:
    external: true