FROM seldonio/mlserver:1.6.0

# Install the required Python packages
RUN pip install mlflow==2.17.2 \
    cloudpickle==3.1.0 \
    langchain-community==0.3.5 \
    langchain==0.3.7 \
    numpy==1.26.4 \
    openai==1.54.0 \
    pydantic==2.9.2 \
    rich==13.9.4