LDAP_PORT_NUMBER: 1389
service:
  # port: 389 # i hardcoded this in the service.yaml
  type: ClusterIP
  # nodePort: 30000 
## secrets
secrets:
  LDAP_ADMIN_USERNAME: topg
  LDAP_ADMIN_PASSWORD: supahakka
  LDAP_ROOT: dc=dolphin,dc=lmao